openapi: 3.0.0
info:
  description: This API receives User information when the user created new account
  version: "1.0.0"
  title: User account registration API
  contact:
    email: slim107@my.bcit.ca
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: user account
    description: user created new account as student or instructor
paths:
  /account/student:
    post:
      tags:
        - user account
      summary: user created as student
      operationId: app.student_account
      description: Adds a new student account information to the system
      responses:
        "201":
          description: student account created
        "400":
          description: "invalid input, object invalid"
        # '409':
        #   description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Student"
        description: account to add

  /account/instructor:
    post:
      tags:
        - user account
      summary: account created as instructor
      operationId: app.instructor_account
      description: Adds an instructor account information to the system
      responses:
        "201":
          description: instructor account created
        "400":
          description: "invalid input, object invalid"
        # '409':
        #   description: an existing item already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Instructor"
        description: account to add

components:
  schemas:
    Student:
      type: object
      required:
        - fullname
        - username
        - password
        - final_grade
      properties:
        fullname:
          type: string
          example: john kim
        username:
          type: string
          example: john123123
        password:
          type: string
          example: q1w2e3r4
        final_grade:
          type: integer
          example: 95

    Instructor:
      required:
        - fullname
        - username
        - password
        - classes
      properties:
        fullname:
          type: string
          example: Sean lim
        username:
          type: string
          example: sushi123
        password:
          type: string
          example: 123123qwer
        classes:
          $ref: "#/components/schemas/Classes"

    Classes:
      required:
        - math
        - python
      properties:
        math:
          type: string
          example: MATH3800
        python:
          type: string
          example: ACIT2512
      type: object
