openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: slim107@my.bcit.ca


paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets a new student and instructor account processed statistics
      responses:
        '200':
          description: Successfully returned a list of student and instrcutor account events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/EventStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    EventStats:
      required:
        - num_score_events
        - highest_score
        - lowest_score
        - num_in_events
        - last_updated
      properties:
        num_score_events:
          type: integer
          example: 1000
        highest_score:
          type: integer
          example: 100
        lowest_score:
          type: integer
          example: 500
        num_in_events:
          type: integer
          example: 1000
        last_updated:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
      type: object